# Generated by Django 5.0.1 on 2024-01-16 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('starting_balance', models.FloatField(default=0)),
                ('growth', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActualReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('day', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='associated user')),
            ],
        ),
        migrations.CreateModel(
            name='Journaal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=70)),
                ('session', models.CharField(max_length=100)),
                ('pips', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('entry_time', models.CharField(max_length=70)),
                ('comment', models.CharField(max_length=100)),
                ('chart_before', models.URLField(max_length=100)),
                ('chart_after', models.URLField(max_length=70)),
                ('profit', models.CharField(max_length=70)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField(blank=True)),
                ('milestone_timeline', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('opportunities', models.TextField(blank=True)),
                ('threats', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
